### ISSUE TITLE
您这个对应的板子是哪个？

### ISSUE THREAD

**Issue by Berte-Yu** [github-ljw-github/u-boot-2014.07-jianwei-samsung-s5p6818#2]
是自己设计的？
还是哪家公司的？

**Comment by github-ljw-github** [comment]
三星 S5P6818

**Comment by Berte-Yu** [comment]
主控是S5P6818，板子呢？

我现在手里有个二手的葡萄雨的s5p6818开发板，但是板子资料被我弄没了，现在到处找呢，想问问您这是哪个板子的，有没有资料`核心板原理图或者底板原理图`可以给我分享一份，谢谢了，

**Comment by github-ljw-github** [comment]
得收费





------------------ 原始邮件 ------------------
From: Berte-Yu ***@***.***&gt;
发送时间: 09/14/2021, 09:32
To: github-ljw-github/u-boot-2014.07-jianwei-samsung-s5p6818 ***@***.***&gt;
抄送: github-ljw-github ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Reply:[github-ljw-github/u-boot-2014.07-jianwei-samsung-s5p6818] 您这个对应的板子是哪个？ (#2)





 
主控是S5P6818，板子呢？
 
我现在手里有个二手的葡萄雨的s5p6818开发板，但是板子资料被我弄没了，现在到处找呢，想问问您这是哪个板子的，有没有资料核心板原理图或者底板原理图可以给我分享一份，谢谢了，
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Berte-Yu** [comment]
好吧  那打扰了
